version: "3.2"
services:
  ch-server-1:
    image: yandex/clickhouse-server
    volumes:
      - ./configs/config.xml:/etc/clickhouse-server/config.xml
      - ./configs/macros1.xml:/etc/clickhouse-server/conf.d/macros.xml
      - ./configs/port1.xml:/etc/clickhouse-server/conf.d/port.xml
      - ./configs/clickhouse_remote_servers.xml:/etc/clickhouse-server/conf.d/clickhouse_remote_servers.xml
      - ./configs/zookeeper-servers.xml:/etc/clickhouse-server/conf.d/zookeeper-servers.xml
      - ./data/1:/var/lib/clickhouse
    ports:
      - 18123:8123
      - 9001:9001

  ch-server-2:
    image: yandex/clickhouse-server
    volumes:
      - ./configs/config.xml:/etc/clickhouse-server/config.xml
      - ./configs/macros2.xml:/etc/clickhouse-server/conf.d/macros.xml
      - ./configs/port2.xml:/etc/clickhouse-server/conf.d/port.xml
      - ./configs/clickhouse_remote_servers.xml:/etc/clickhouse-server/conf.d/clickhouse_remote_servers.xml
      - ./configs/zookeeper-servers.xml:/etc/clickhouse-server/conf.d/zookeeper-servers.xml
      - ./data/2:/var/lib/clickhouse
    ports:
      - 28123:8123
      - 9002:9002

  ch-server-3:
    image: yandex/clickhouse-server
    volumes:
      - ./configs/config.xml:/etc/clickhouse-server/config.xml
      - ./configs/macros3.xml:/etc/clickhouse-server/conf.d/macros.xml
      - ./configs/port3.xml:/etc/clickhouse-server/conf.d/port.xml
      - ./configs/clickhouse_remote_servers.xml:/etc/clickhouse-server/conf.d/clickhouse_remote_servers.xml
      - ./configs/zookeeper-servers.xml:/etc/clickhouse-server/conf.d/zookeeper-servers.xml
      - ./data/3:/var/lib/clickhouse
    ports:
      - 38123:8123
      - 9003:9003

  ch-server-4:
    image: yandex/clickhouse-server
    volumes:
      - ./configs/config.xml:/etc/clickhouse-server/config.xml
      - ./configs/macros4.xml:/etc/clickhouse-server/conf.d/macros.xml
      - ./configs/port4.xml:/etc/clickhouse-server/conf.d/port.xml
      - ./configs/clickhouse_remote_servers.xml:/etc/clickhouse-server/conf.d/clickhouse_remote_servers.xml
      - ./configs/zookeeper-servers.xml:/etc/clickhouse-server/conf.d/zookeeper-servers.xml
      - ./data/4:/var/lib/clickhouse
    ports:
      - 48123:8123
      - 9004:9004

  ch-server-5:
    image: yandex/clickhouse-server
    volumes:
      - ./configs/config.xml:/etc/clickhouse-server/config.xml
      - ./configs/macros5.xml:/etc/clickhouse-server/conf.d/macros.xml
      - ./configs/port5.xml:/etc/clickhouse-server/conf.d/port.xml
      - ./configs/clickhouse_remote_servers.xml:/etc/clickhouse-server/conf.d/clickhouse_remote_servers.xml
      - ./configs/zookeeper-servers.xml:/etc/clickhouse-server/conf.d/zookeeper-servers.xml
      - ./data/5:/var/lib/clickhouse

  ch-server-6:
    image: yandex/clickhouse-server
    volumes:
      - ./configs/config.xml:/etc/clickhouse-server/config.xml
      - ./configs/macros6.xml:/etc/clickhouse-server/conf.d/macros.xml
      - ./configs/port6.xml:/etc/clickhouse-server/conf.d/port.xml
      - ./configs/clickhouse_remote_servers.xml:/etc/clickhouse-server/conf.d/clickhouse_remote_servers.xml
      - ./configs/zookeeper-servers.xml:/etc/clickhouse-server/conf.d/zookeeper-servers.xml
      - ./data/6:/var/lib/clickhouse

  ch-client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity

  zoo1:
    image: zookeeper
    volumes:
      - ./data/zoo1:/data
    ports:
      - 2181:2181
      - 38881:3888
      - 28881:2888
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:28881:38881 server.2=zoo2:28882:38882 server.3=zoo3:28883:38883

  zoo2:
    image: zookeeper
    volumes:
      - ./data/zoo2:/data
    ports:
      - 2182:2181
      - 38882:3888
      - 28882:2888
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:28881:38881 server.2=zoo2:28882:38882 server.3=zoo3:28883:38883

  zoo3:
    image: zookeeper
    volumes:
      - ./data/zoo3:/data
    ports:
      - 2183:2181
      - 38883:3888
      - 28883:2888
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:28881:38881 server.2=zoo2:28882:38882 server.3=zoo3:28883:38883

  superset:
    image: divvit/divvit-superset
    volumes:
      - ./data/superset:/home/superset
    ports:
      - 8088:8088

